name: BasicSpawnProtection
main: pmmp\BasicSpawnProtection\Main
src-namespace-prefix: pmmp\BasicSpawnProtection
version: 2.0.1+dev
api: 5.0.0
load: POSTWORLD
author: pmmp
description: Protect a radius around your worlds' spawn from modification
website: https://github.com/pmmp/BasicSpawnProtection
permissions:
  basicspawnprotect.bypass:
    description: Allows the user to bypass the spawn protection zone
    default: op
